### PR TITLE
Add json endpoint for hiscores

### PR DESCRIPTION
**Pull request by pjoeterbliep**
Tested it, seems to work.

### CODE REVIEW

**Comment by DrYoshiyahu** [comment]
Amazing! What a quick turnaround! <3

**Comment by leejt** [comment]
Is there a reason we want to support both endpoints? Can you just replace the existing functionality rather than supporting both json and ws?

**Comment by wgevaert** [comment]
Backwards compatibility mostly. You dont want all tools to break when we deploy this right?

Or maybe you do

Code would for sure be simpler if we allow only one endpoint

**Comment by pjoeterbliep** [comment]
I made a pull request that breaks backwards compatibility [here](https://github.com/weirdgloop/mediawiki-extensions-RSHiscores/pull/3), it also fixes [issue 1](https://github.com/weirdgloop/mediawiki-extensions-RSHiscores/issues/1). We can merge one of the two and close the other.

**Comment by DrYoshiyahu** [comment]
I think it's completely fine to break backwards compatibility and forget the ws endpoint. There are so few tools that actually use this plugin, and it's a very easy fix.

**Comment by pjoeterbliep** [comment]
Closed in favor of https://github.com/weirdgloop/mediawiki-extensions-RSHiscores/pull/3
Consensus seems to be to break backwards compatibility while implementing this feature, which is what that pull request does

**Pull request closed without merging**
